version: '1'
services:
  web:
    build: .
    ports:
      - "4200:4200"
    volumes:
      - .:/angular
      - angular:/var/log
    links:
      - redis
    node:
    image: node
volumes:
    angular: {

    }
